version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: weather-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=weather-monitoring
      - DOCKER_INFLUXDB_INIT_BUCKET=weather-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-super-secret-admin-token
      - TZ=UTC
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: weather-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - TZ=UTC
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    restart: unless-stopped

  weather-monitor:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather-monitor
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=your-super-secret-admin-token
      - INFLUXDB_ORG=weather-monitoring
      - INFLUXDB_BUCKET=weather-data
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_STATION_ID=${WEATHER_STATION_ID}
      - LOG_LEVEL=INFO
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
  influxdb_config:
  grafana_data: