global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  # Docker containers (if docker daemon metrics are exposed)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 5s
    metrics_path: /metrics

  # Weather application custom metrics (if we add them later)
  - job_name: 'weather-app'
    static_configs:
      - targets: ['weather-monitor:8000']  # We can add metrics endpoint later
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s